### ISSUE TITLE
request for a how-to-use guide

### ISSUE THREAD

**Issue by prclibo** [ptone/everdisq#1]
Hello Preston Holmes,
I was searching for methods to add comment on my evernote notes and find this repo seems to be the only workaround. However I am not an expert in web programming. So I would like to ask if you can share some detailed guide on how to use this repo and set up it on my notes. Thank you.

**Comment by ptone** [comment]
Sorry - this was sort of a quick hack - hopefully to pressure Evernote in
to adding feature.

I use to run a hosted version - but that domain expired.

Sorry - it is not software, and I'm not able to put together user-level
docs.

-P

**Comment by prclibo** [comment]
Hi, yes I understand this is just a quick hack. Thanks for the reply. After studying some flask basics yesterday I guess I can setup it by myself now.
One question to confirm: the comments are not rendered in notes but in a page holding the note, right?

**Comment by ptone** [comment]
Yes - the comments are rendered by the disqus service, and the page just associates them with a evernote shared item
